<?php

namespace App\Http\Controllers;

use App\Models\{Quiz, Lesson, QuizAttempt, QuizQuestion};
use App\Services\BadgeService;
use Illuminate\Http\{Request, JsonResponse};
use Illuminate\Support\Facades\{Http, DB, Log};
use Exception;
use Throwable;

class QuizController extends Controller
{
    private const MAX_QUESTIONS = 25;

    public function generateAndStoreQuiz(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                'lesson_id'       => 'required|exists:lessons,id',
                'title'           => 'required|string|max:255',
                'questions_count' => 'nullable|integer|min:3|max:25',
            ]);

            $lesson = Lesson::findOrFail($validated['lesson_id']);
            $cleanContent = mb_substr(strip_tags($lesson->content), 0, 5000);
            $count = $validated['questions_count'] ?? 5;

            if (!config('services.openai.key')) {
                throw new Exception("La clé OPENAI_API_KEY est manquante dans votre fichier .env ou config/services.php");
            }

            $questions = $this->fetchAiQuestions($cleanContent, $lesson->title, $count);

            $quiz = DB::transaction(function () use ($lesson, $validated, $questions) {
                $quiz = Quiz::create([
                    'lesson_id'     => $lesson->id,
                    'title'         => $validated['title'],
                    'description'   => "Auto-generated by AI based on: {$lesson->title}",
'passing_score' => $validated['passing_score'] ?? 70,
                    'questions_count' => count($questions),
                    'is_published'  => true,
                ]);

                foreach ($questions as $idx => $q) {
                    if (!isset($q['question_text'], $q['options'])) continue;

                    $quiz->questions()->create([
                        'question_text'  => $q['question_text'],
                        'question_type'  => $q['question_type'] ?? 'multiple_choice',
                        'difficulty'     => $q['difficulty'] ?? 'medium',
                        'correct_answer' => $q['correct_answer'] ?? 'A) Error',
                        'options'        => is_array($q['options']) ? json_encode($q['options']) : $q['options'],
                        'points'         => $this->calculatePoints($q['difficulty'] ?? 'medium'),
                        'order'          => $idx,
                    ]);
                }
                return $quiz->load('questions');
            });

            return response()->json([
                'success'  => true,
                'id'       => $quiz->id,
                'quiz_id'  => $quiz->id,
                'quiz'     => $quiz,
                'message'  => 'Quiz generated successfully!'
            ], 201);

        } catch (Throwable $e) {
            Log::error('QUIZ_GENERATION_ERROR', [
                'msg'   => $e->getMessage(),
                'file'  => $e->getFile(),
                'line'  => $e->getLine(),
                'trace' => $e->getTraceAsString()
            ]);

            $message = $e->getMessage();
            if (strpos($message, 'quota') !== false || strpos($message, '429') !== false) {
                $message = "OpenAI API quota exceeded. Fallback questions are being used.";
            } elseif (strpos($message, 'API key') !== false) {
                $message = "OpenAI API key not configured. Using fallback questions.";
            } elseif (empty($message)) {
                $message = "An error occurred during quiz generation.";
            }

            return response()->json([
                'success' => false,
                'error'   => 'Quiz Generation Error',
                'message' => $message,
            ], 500);
        }
    }

    private function fetchAiQuestions(string $content, string $title, int $count): array
    {
        try {
            $apiKey = config('services.openai.key');
            if (!$apiKey || empty(trim($apiKey))) {
                throw new Exception("OpenAI API key is not configured in .env file");
            }

            $systemPrompt = <<<'PROMPT'
You are an expert educational quiz creator. Generate high-quality quiz questions based on provided content.
Return ONLY valid JSON. No markdown, no code blocks, just pure JSON.
PROMPT;

            $userPrompt = <<<PROMPT
Create exactly $count quiz questions about "$title" based on this content:

$content

Generate questions with:
1. Mix of difficulty levels (easy, medium, hard)
2. Clear, specific questions
3. 4 multiple choice options (A, B, C, D)
4. Exactly ONE correct answer

Return JSON in this exact format:
{
  "questions": [
    {
      "question_text": "Question here?",
      "question_type": "multiple_choice",
      "difficulty": "medium",
      "options": ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
      "correct_answer": "B) Option 2"
    }
  ]
}

IMPORTANT:
- Generate exactly $count questions
- Ensure all options are different
- Make correct_answer match one of the options exactly
- Vary difficulty: easy (30%), medium (50%), hard (20%)
- Questions should test understanding, not just recall
PROMPT;

            $response = Http::withToken($apiKey)
                ->timeout(120)
                ->retry(2, 100)
                ->post('https://api.openai.com/v1/chat/completions', [
                    'model'           => 'gpt-4o-mini',
                    'messages'        => [
                        ['role' => 'system', 'content' => $systemPrompt],
                        ['role' => 'user',   'content' => $userPrompt],
                    ],
                    'response_format' => ['type' => 'json_object'],
                    'temperature'     => 0.7,
                    'max_tokens'      => 3000,
                ]);

            if (!$response->successful()) {
                $status = $response->status();
                $body   = $response->body();

                Log::error('OpenAI API Error', [
                    'status' => $status,
                    'body'   => substr($body, 0, 500)
                ]);

                if ($status === 429) {
                    throw new Exception("OpenAI API rate limited or quota exceeded. Please try again later or check your API quota.");
                } elseif ($status === 401) {
                    throw new Exception("Invalid OpenAI API key. Please check your .env configuration.");
                } else {
                    throw new Exception("OpenAI API error ({$status}): " . substr($body, 0, 200));
                }
            }

            $data = $response->json();

            if (!isset($data['choices'][0]['message']['content'])) {
                throw new Exception("Invalid OpenAI response format - missing content");
            }

            $content = $data['choices'][0]['message']['content'];
            $decoded = json_decode($content, true);

            if (!$decoded || !isset($decoded['questions']) || empty($decoded['questions'])) {
                throw new Exception("No questions generated from OpenAI response");
            }

            return $decoded['questions'];

        } catch (\Exception $e) {
            Log::error('Quiz AI Generation Failed', [
                'error' => $e->getMessage(),
                'file'  => $e->getFile(),
                'line'  => $e->getLine()
            ]);

            return $this->generateMockQuestions($title, $count);
        }
    }

    /**
     * Generate mock/fallback questions when AI is unavailable.
     * Contains 25 questions per topic: Routes, Middleware, Axios,
     * Controllers, Models, Migrations, Validation, Auth.
     * Questions are selected by cycling through the matching topic bank
     * (or the general bank if no topic matches).
     */
    private function generateMockQuestions(string $topic, int $count): array
    {
        $count = min($count, self::MAX_QUESTIONS);

        // ── 25 questions per topic ────────────────────────────────────────────
        $banks = [

            // ── ROUTES ───────────────────────────────────────────────────────
            'route' => [
                ['q'=>'What is the purpose of routes in Laravel?',                                  'd'=>'easy',   'o'=>['A) Manage DB tables','B) Define application endpoints','C) Style the UI','D) Compile JS'],                                       'a'=>'B) Define application endpoints'],
                ['q'=>'Which HTTP method is used to fetch data without side effects?',               'd'=>'easy',   'o'=>['A) POST','B) DELETE','C) GET','D) PUT'],                                                                                         'a'=>'C) GET'],
                ['q'=>'Which HTTP method is typically used to update existing data?',                'd'=>'medium', 'o'=>['A) GET','B) POST','C) PUT/PATCH','D) DELETE'],                                                                                   'a'=>'C) PUT/PATCH'],
                ['q'=>'What is a dynamic route parameter in Laravel?',                               'd'=>'hard',   'o'=>['A) A fixed URL segment','B) A variable value in the URL','C) A CSS class','D) A DB column'],                                    'a'=>'B) A variable value in the URL'],
                ['q'=>'Which method creates a resourceful route in Laravel?',                        'd'=>'medium', 'o'=>['A) Route::resource()','B) Route::get()','C) Route::post()','D) Route::put()'],                                                   'a'=>'A) Route::resource()'],
                ['q'=>'How do you name a route in Laravel?',                                         'd'=>'medium', 'o'=>["A) ->name('name')","B) ->as('name')","C) ->label('name')","D) Both A and B"],                                                   'a'=>"D) Both A and B"],
                ['q'=>'Which file contains web routes in a default Laravel project?',                'd'=>'easy',   'o'=>['A) routes/api.php','B) routes/web.php','C) app/routes.php','D) config/routes.php'],                                             'a'=>'B) routes/web.php'],
                ['q'=>'Which file contains API routes in Laravel?',                                  'd'=>'easy',   'o'=>['A) routes/web.php','B) routes/console.php','C) routes/api.php','D) routes/channels.php'],                                       'a'=>'C) routes/api.php'],
                ['q'=>'How do you group routes under a common prefix?',                              'd'=>'medium', 'o'=>["A) Route::group(['prefix' => 'admin'], ...)","B) Route::prefix('admin')->group(...)","C) Both A and B","D) Route::path('admin')"], 'a'=>'C) Both A and B'],
                ['q'=>'What artisan command lists all registered routes?',                           'd'=>'easy',   'o'=>['A) php artisan route:list','B) php artisan show:routes','C) php artisan routes','D) php artisan route:show'],                    'a'=>'A) php artisan route:list'],
                ['q'=>'How do you apply middleware to a route?',                                     'd'=>'medium', 'o'=>["A) Route::get('/path', fn)->with('auth')","B) Route::get('/path', fn)->middleware('auth')","C) Route::auth('/path', fn)","D) Route::get('/path', fn)->guard('auth')"], 'a'=>"B) Route::get('/path', fn)->middleware('auth')"],
                ['q'=>'What does Route::fallback() do?',                                             'd'=>'hard',   'o'=>['A) Redirects all traffic','B) Handles unmatched routes (404 fallback)','C) Caches routes','D) Defines default controller'],     'a'=>'B) Handles unmatched routes (404 fallback)'],
                ['q'=>'How do you redirect one route to another in Laravel?',                        'd'=>'medium', 'o'=>["A) Route::redirect('/from','/to')","B) Route::move('/from','/to')","C) Route::forward('/from','/to')","D) Route::go('/from','/to')"], 'a'=>"A) Route::redirect('/from','/to')"],
                ['q'=>'What is route model binding?',                                                'd'=>'hard',   'o'=>['A) Binding a model name to a DB table','B) Auto-injecting a model instance via a route parameter','C) Attaching middleware to a model','D) Caching model queries in routes'], 'a'=>'B) Auto-injecting a model instance via a route parameter'],
                ['q'=>'Which method returns the URL for a named route?',                             'd'=>'medium', 'o'=>["A) url('name')","B) link('name')","C) route('name')","D) path('name')"],                                                         'a'=>"C) route('name')"],
                ['q'=>'How do you define an optional route parameter?',                              'd'=>'hard',   'o'=>['A) {param}','B) [param]','C) {param?}','D) (param)'],                                                                           'a'=>'C) {param?}'],
                ['q'=>'What does Route::any() do?',                                                  'd'=>'medium', 'o'=>['A) Matches only GET and POST','B) Matches any HTTP verb','C) Matches authenticated requests','D) Matches wildcard URLs'],         'a'=>'B) Matches any HTTP verb'],
                ['q'=>'How do you constrain a route parameter to digits only?',                      'd'=>'hard',   'o'=>["A) ->where('id','[0-9]+')","B) ->only('id','numeric')","C) ->constraint('id','digits')","D) ->validate('id','number')"],         'a'=>"A) ->where('id','[0-9]+')"],
                ['q'=>'Which HTTP verb does Route::patch() represent?',                              'd'=>'easy',   'o'=>['A) Full update','B) Partial update','C) Delete','D) Read'],                                                                     'a'=>'B) Partial update'],
                ['q'=>'How do you cache routes for performance?',                                    'd'=>'hard',   'o'=>['A) php artisan route:cache','B) php artisan optimize:routes','C) php artisan cache:routes','D) php artisan config:cache'],        'a'=>'A) php artisan route:cache'],
                ['q'=>'What is a route domain constraint used for?',                                 'd'=>'hard',   'o'=>['A) Restricting routes to specific subdomains','B) Limiting route parameters to numbers','C) Grouping routes by controller','D) Adding CORS headers'], 'a'=>'A) Restricting routes to specific subdomains'],
                ['q'=>'Which method defines a route that responds to multiple HTTP verbs?',          'd'=>'medium', 'o'=>["A) Route::match(['get','post'], ...)","B) Route::multi(...)","C) Route::verbs(...)","D) Route::combined(...)"],                   'a'=>"A) Route::match(['get','post'], ...)"],
                ['q'=>'What is the default namespace for route-bound controllers in Laravel 8+?',    'd'=>'hard',   'o'=>['A) App\\Http\\Controllers','B) No default namespace; FQCN required','C) Controllers\\','D) App\\Controllers'],                   'a'=>'B) No default namespace; FQCN required'],
                ['q'=>'How do you generate a signed URL for a named route?',                         'd'=>'hard',   'o'=>["A) URL::signedRoute('name', params)","B) route()->sign('name')","C) Route::signed('name')","D) URL::secure('name')"],            'a'=>"A) URL::signedRoute('name', params)"],
                ['q'=>'What is the purpose of rate limiting in routes (throttle middleware)?',       'd'=>'medium', 'o'=>['A) Speed up routing','B) Limit request frequency per user','C) Cache route responses','D) Validate route parameters'],           'a'=>'B) Limit request frequency per user'],
            ],

            // ── MIDDLEWARE ────────────────────────────────────────────────────
            'middleware' => [
                ['q'=>'What is middleware in Laravel?',                                              'd'=>'easy',   'o'=>['A) A database layer','B) HTTP request/response filter','C) A Blade directive','D) An Artisan command'],                          'a'=>'B) HTTP request/response filter'],
                ['q'=>'Where are global middleware registered in Laravel?',                          'd'=>'medium', 'o'=>['A) app/Http/Kernel.php','B) config/middleware.php','C) routes/web.php','D) bootstrap/app.php'],                                  'a'=>'A) app/Http/Kernel.php'],
                ['q'=>'Which built-in middleware checks if a user is authenticated?',                'd'=>'easy',   'o'=>['A) verified','B) guest','C) auth','D) throttle'],                                                                               'a'=>'C) auth'],
                ['q'=>'Which middleware prevents authenticated users from accessing guest-only pages?','d'=>'easy', 'o'=>['A) auth','B) guest','C) verified','D) signed'],                                                                                  'a'=>'B) guest'],
                ['q'=>'How do you create a new middleware in Laravel?',                              'd'=>'easy',   'o'=>['A) php artisan make:middleware Name','B) php artisan create:middleware Name','C) php artisan generate:middleware Name','D) php artisan new:middleware Name'], 'a'=>'A) php artisan make:middleware Name'],
                ['q'=>'What method must a middleware class implement?',                              'd'=>'medium', 'o'=>['A) run()','B) execute()','C) handle()','D) process()'],                                                                         'a'=>'C) handle()'],
                ['q'=>'How do you pass the request to the next middleware?',                         'd'=>'medium', 'o'=>['A) return next()','B) return $next($request)','C) continue($request)','D) forward($request)'],                                  'a'=>'B) return $next($request)'],
                ['q'=>'What is a terminable middleware?',                                            'd'=>'hard',   'o'=>['A) Middleware that stops the request','B) Middleware that runs after the response is sent','C) Middleware for API termination','D) Middleware that caches responses'], 'a'=>'B) Middleware that runs after the response is sent'],
                ['q'=>'How do you apply middleware to all routes in a group?',                       'd'=>'medium', 'o'=>["A) Route::group(['middleware' => 'auth'], ...)","B) Route::middleware('auth')->group(...)","C) Both A and B","D) Route::all()->middleware('auth')"], 'a'=>'C) Both A and B'],
                ['q'=>'Which middleware property stores route-specific middleware aliases?',         'd'=>'hard',   'o'=>['A) $middleware','B) $middlewareGroups','C) $routeMiddleware / $middlewareAliases','D) $namedMiddleware'],                         'a'=>'C) $routeMiddleware / $middlewareAliases'],
                ['q'=>'What is the purpose of the "web" middleware group?',                          'd'=>'medium', 'o'=>['A) API authentication','B) Session, CSRF, cookies for web routes','C) Throttling requests','D) Validating JSON payloads'],       'a'=>'B) Session, CSRF, cookies for web routes'],
                ['q'=>'What is the purpose of the "api" middleware group?',                          'd'=>'medium', 'o'=>['A) Session and cookies','B) Stateless throttling for API routes','C) CSRF protection','D) View rendering'],                      'a'=>'B) Stateless throttling for API routes'],
                ['q'=>'How do you exclude a middleware for specific routes?',                        'd'=>'hard',   'o'=>["A) ->withoutMiddleware(Name::class)","B) ->skipMiddleware(Name::class)","C) ->except(Name::class)","D) ->removeMiddleware(Name::class)"], 'a'=>"A) ->withoutMiddleware(Name::class)"],
                ['q'=>'What does the VerifyCsrfToken middleware do?',                                'd'=>'medium', 'o'=>['A) Validates JSON','B) Protects against Cross-Site Request Forgery','C) Encrypts cookies','D) Rate-limits requests'],            'a'=>'B) Protects against Cross-Site Request Forgery'],
                ['q'=>'Where can you add a URI to CSRF exception list?',                             'd'=>'hard',   'o'=>['A) $except array in VerifyCsrfToken','B) config/csrf.php','C) routes/web.php','D) bootstrap/app.php'],                           'a'=>'A) $except array in VerifyCsrfToken'],
                ['q'=>'Which middleware handles signed URL verification?',                           'd'=>'hard',   'o'=>['A) auth','B) signed','C) verified','D) secure'],                                                                                'a'=>'B) signed'],
                ['q'=>'What does the "throttle:60,1" middleware mean?',                              'd'=>'medium', 'o'=>['A) 60 requests per second','B) 60 requests per minute','C) 1 request per 60 seconds','D) 60 KB per request'],                    'a'=>'B) 60 requests per minute'],
                ['q'=>'How do you pass parameters to middleware?',                                   'd'=>'hard',   'o'=>["A) ->middleware('role:admin')","B) ->middleware('role', 'admin')","C) ->with('role','admin')","D) ->param('role','admin')"],      'a'=>"A) ->middleware('role:admin')"],
                ['q'=>'Which middleware encrypts cookies in Laravel?',                               'd'=>'medium', 'o'=>['A) SessionMiddleware','B) EncryptCookies','C) SecureCookies','D) CryptoMiddleware'],                                             'a'=>'B) EncryptCookies'],
                ['q'=>'What does SubstituteBindings middleware do?',                                 'd'=>'hard',   'o'=>['A) Replaces route parameters with model instances','B) Substitutes env variables','C) Replaces request inputs','D) Maps middleware aliases'], 'a'=>'A) Replaces route parameters with model instances'],
                ['q'=>'Can middleware modify the response before returning it?',                     'd'=>'medium', 'o'=>['A) No, only the request','B) Yes, by modifying $response after $next($request)','C) Only in API mode','D) Only global middleware can'], 'a'=>'B) Yes, by modifying $response after $next($request)'],
                ['q'=>'What is the correct order of middleware execution?',                         'd'=>'hard',   'o'=>['A) Last registered runs first','B) First registered runs first (FIFO)','C) Alphabetical order','D) Random order'],               'a'=>'B) First registered runs first (FIFO)'],
                ['q'=>'How do you register a global middleware in Laravel 11+?',                     'd'=>'hard',   'o'=>['A) In bootstrap/app.php using ->withMiddleware()','B) In app/Http/Kernel.php $middleware array','C) In config/app.php','D) In routes/web.php'], 'a'=>'A) In bootstrap/app.php using ->withMiddleware()'],
                ['q'=>'What does the HandleCors middleware manage?',                                 'd'=>'medium', 'o'=>['A) Cookie encryption','B) Cross-Origin Resource Sharing headers','C) CSRF tokens','D) Session expiration'],                      'a'=>'B) Cross-Origin Resource Sharing headers'],
                ['q'=>'When does middleware run relative to the controller?',                        'd'=>'easy',   'o'=>['A) After controller','B) Simultaneously','C) Before controller (and optionally after)','D) Only on errors'],                     'a'=>'C) Before controller (and optionally after)'],
            ],

            // ── AXIOS ─────────────────────────────────────────────────────────
            'axios' => [
                ['q'=>'What is Axios?',                                                               'd'=>'easy',   'o'=>['A) A CSS framework','B) A promise-based HTTP client for JS','C) A backend PHP library','D) A state management tool'],           'a'=>'B) A promise-based HTTP client for JS'],
                ['q'=>'How do you install Axios via npm?',                                            'd'=>'easy',   'o'=>['A) npm install axios','B) npm add http-axios','C) npm get axios','D) npm fetch axios'],                                         'a'=>'A) npm install axios'],
                ['q'=>'How do you make a GET request with Axios?',                                    'd'=>'easy',   'o'=>["A) axios.fetch('/url')","B) axios.get('/url')","C) axios.retrieve('/url')","D) axios.read('/url')"],                             'a'=>"B) axios.get('/url')"],
                ['q'=>'How do you make a POST request with Axios?',                                   'd'=>'easy',   'o'=>["A) axios.send('/url', data)","B) axios.post('/url', data)","C) axios.submit('/url', data)","D) axios.create('/url', data)"],     'a'=>"B) axios.post('/url', data)"],
                ['q'=>'How do you set a global Authorization header in Axios?',                       'd'=>'medium', 'o'=>["A) axios.defaults.headers.common['Authorization'] = token","B) axios.setHeader('Authorization', token)","C) axios.global.auth = token","D) axios.config.token = token"], 'a'=>"A) axios.defaults.headers.common['Authorization'] = token"],
                ['q'=>'What does axios.create() do?',                                                 'd'=>'medium', 'o'=>['A) Creates an Axios plugin','B) Creates a new Axios instance with custom config','C) Creates a POST request','D) Initialises a new HTTP server'], 'a'=>'B) Creates a new Axios instance with custom config'],
                ['q'=>'How do you handle errors in an Axios request?',                                'd'=>'medium', 'o'=>['.then()/.catch()','try/catch with async/await','Both A and B','D) axios.onError()'],                                            'a'=>'C) Both A and B'],
                ['q'=>'What property of the Axios response contains the response data?',              'd'=>'easy',   'o'=>['A) response.body','B) response.result','C) response.data','D) response.payload'],                                              'a'=>'C) response.data'],
                ['q'=>'How do you add a request interceptor in Axios?',                               'd'=>'hard',   'o'=>['A) axios.before(fn)','B) axios.interceptors.request.use(fn)','C) axios.middleware(fn)','D) axios.onRequest(fn)'],               'a'=>'B) axios.interceptors.request.use(fn)'],
                ['q'=>'How do you add a response interceptor in Axios?',                              'd'=>'hard',   'o'=>['A) axios.afterResponse(fn)','B) axios.interceptors.response.use(fn)','C) axios.onResponse(fn)','D) axios.pipe(fn)'],            'a'=>'B) axios.interceptors.response.use(fn)'],
                ['q'=>'How do you cancel an Axios request?',                                          'd'=>'hard',   'o'=>['A) axios.abort()','B) Using AbortController or CancelToken','C) request.cancel()','D) axios.stop()'],                           'a'=>'B) Using AbortController or CancelToken'],
                ['q'=>'How do you set a timeout for an Axios request?',                               'd'=>'medium', 'o'=>["A) axios.get(url, { timeout: 5000 })","B) axios.get(url, { maxTime: 5000 })","C) axios.get(url, { wait: 5000 })","D) axios.get(url, { limit: 5000 })"], 'a'=>"A) axios.get(url, { timeout: 5000 })"],
                ['q'=>'What is the default Content-Type Axios uses for POST requests?',               'd'=>'medium', 'o'=>['A) text/plain','B) multipart/form-data','C) application/json','D) application/x-www-form-urlencoded'],                          'a'=>'C) application/json'],
                ['q'=>'How do you send FormData (file upload) with Axios?',                           'd'=>'hard',   'o'=>["A) axios.post(url, formData, { headers: {'Content-Type': 'multipart/form-data'} })","B) axios.upload(url, formData)","C) axios.file(url, formData)","D) axios.post(url, formData) — Axios auto-detects"], 'a'=>"A) axios.post(url, formData, { headers: {'Content-Type': 'multipart/form-data'} })"],
                ['q'=>'How do you send query parameters with an Axios GET request?',                  'd'=>'medium', 'o'=>["A) axios.get(url, { params: { key: 'value' } })","B) axios.get(url+'?key=value') only","C) axios.get(url, { query: { key: 'value' } })","D) axios.query(url, { key: 'value' })"], 'a'=>"A) axios.get(url, { params: { key: 'value' } })"],
                ['q'=>'How do you make multiple concurrent requests with Axios?',                     'd'=>'hard',   'o'=>['A) axios.all([req1, req2])','B) Promise.all([axios.get(...), axios.get(...)])','C) Both A and B','D) axios.concurrent([req1, req2])'], 'a'=>'C) Both A and B'],
                ['q'=>'What HTTP status code range does Axios treat as an error by default?',         'd'=>'hard',   'o'=>['A) 400–499 only','B) 500+ only','C) Any status outside 2xx','D) Any status outside 2xx–3xx'],                                    'a'=>'C) Any status outside 2xx'],
                ['q'=>'How do you include cookies in cross-origin Axios requests?',                   'd'=>'hard',   'o'=>['A) axios.get(url, { cookies: true })','B) axios.get(url, { withCredentials: true })','C) axios.get(url, { credentials: "include" })','D) axios.get(url, { crossOrigin: true })'], 'a'=>'B) axios.get(url, { withCredentials: true })'],
                ['q'=>'What does the validateStatus option in Axios do?',                             'd'=>'hard',   'o'=>['A) Validates request params','B) Defines which HTTP status codes resolve vs reject the promise','C) Validates response JSON schema','D) Checks SSL certificates'], 'a'=>'B) Defines which HTTP status codes resolve vs reject the promise'],
                ['q'=>'How do you send a PUT request with Axios?',                                    'd'=>'easy',   'o'=>["A) axios.update(url, data)","B) axios.put(url, data)","C) axios.patch(url, data) only","D) axios.replace(url, data)"],            'a'=>"B) axios.put(url, data)"],
                ['q'=>'How do you send a PATCH request with Axios?',                                  'd'=>'easy',   'o'=>["A) axios.put(url, data)","B) axios.update(url, data)","C) axios.patch(url, data)","D) axios.modify(url, data)"],                  'a'=>"C) axios.patch(url, data)"],
                ['q'=>'How do you send a DELETE request with Axios?',                                 'd'=>'easy',   'o'=>["A) axios.remove(url)","B) axios.destroy(url)","C) axios.delete(url)","D) axios.del(url)"],                                       'a'=>"C) axios.delete(url)"],
                ['q'=>'How do you add a CSRF token to all Axios requests in Laravel?',                'd'=>'medium', 'o'=>["A) axios.defaults.headers.common['X-CSRF-TOKEN'] = token","B) axios.csrf(token)","C) axios.setToken(token)","D) axios.defaults.csrfToken = token"], 'a'=>"A) axios.defaults.headers.common['X-CSRF-TOKEN'] = token"],
                ['q'=>'What does axios.interceptors.request.eject(id) do?',                          'd'=>'hard',   'o'=>['A) Removes a registered request interceptor','B) Aborts the current request','C) Ejects the Axios instance','D) Clears all headers'],  'a'=>'A) Removes a registered request interceptor'],
                ['q'=>'How can you set a base URL for all Axios requests?',                           'd'=>'medium', 'o'=>["A) axios.defaults.baseURL = 'https://api.example.com'","B) axios.setBase('https://api.example.com')","C) axios.config.url = 'https://api.example.com'","D) axios.root = 'https://api.example.com'"], 'a'=>"A) axios.defaults.baseURL = 'https://api.example.com'"],
            ],

            // ── CONTROLLERS ───────────────────────────────────────────────────
            'controller' => [
                ['q'=>'What is a controller in Laravel?',                                             'd'=>'easy',   'o'=>['A) A DB model','B) A class that handles request logic','C) A Blade template','D) A route file'],                                'a'=>'B) A class that handles request logic'],
                ['q'=>'How do you create a resourceful controller?',                                  'd'=>'easy',   'o'=>['A) php artisan make:controller Name --resource','B) php artisan make:controller Name --rest','C) php artisan make:controller Name --all','D) php artisan resource:controller Name'], 'a'=>'A) php artisan make:controller Name --resource'],
                ['q'=>'Which parent class do Laravel controllers extend by default?',                 'd'=>'easy',   'o'=>['A) BaseController','B) HttpController','C) Controller (App\\Http\\Controllers\\Controller)','D) AbstractController'],           'a'=>'C) Controller (App\\Http\\Controllers\\Controller)'],
                ['q'=>'What are the 7 methods of a resource controller?',                             'd'=>'hard',   'o'=>['A) index, create, store, show, edit, update, destroy','B) list, new, save, view, edit, patch, delete','C) index, new, post, get, edit, put, remove','D) index, create, store, find, form, patch, destroy'], 'a'=>'A) index, create, store, show, edit, update, destroy'],
                ['q'=>'How do you return a JSON response from a controller?',                         'd'=>'easy',   'o'=>["A) return json(['key' => 'value'])","B) return response()->json(['key' => 'value'])","C) return Response::json(['key' => 'value'])","D) Both B and C"], 'a'=>'D) Both B and C'],
                ['q'=>'How do you inject a dependency into a controller constructor?',                'd'=>'medium', 'o'=>['A) Type-hint the class in the constructor','B) Use app()->make()','C) Both A and B','D) Dependency injection is not supported in controllers'], 'a'=>'C) Both A and B'],
                ['q'=>'What does a single-action controller use instead of multiple methods?',        'd'=>'hard',   'o'=>['A) run()','B) __construct()','C) __invoke()','D) execute()'],                                                                   'a'=>'C) __invoke()'],
                ['q'=>'How do you create a single-action controller?',                                'd'=>'medium', 'o'=>['A) php artisan make:controller Name --invokable','B) php artisan make:controller Name --single','C) php artisan make:controller Name --action','D) php artisan invoke:controller Name'], 'a'=>'A) php artisan make:controller Name --invokable'],
                ['q'=>'How do you apply middleware inside a controller constructor?',                 'd'=>'medium', 'o'=>["A) \$this->middleware('auth')","B) \$this->addMiddleware('auth')","C) middleware('auth') standalone","D) \$request->middleware('auth')"], 'a'=>"A) \$this->middleware('auth')"],
                ['q'=>'How do you validate a request inside a controller method?',                    'd'=>'medium', 'o'=>["A) \$request->validate([...])","B) Validator::check([...])","C) validate(\$request, [...])","D) \$this->rules([...])"],           'a'=>"A) \$request->validate([...])"],
                ['q'=>'What is a Form Request in Laravel?',                                           'd'=>'hard',   'o'=>['A) An HTML form tag','B) A custom request class with validation rules','C) A middleware for forms','D) A Blade component'],      'a'=>'B) A custom request class with validation rules'],
                ['q'=>'How do you return a view from a controller?',                                  'd'=>'easy',   'o'=>["A) return view('name')","B) return render('name')","C) return blade('name')","D) return template('name')"],                     'a'=>"A) return view('name')"],
                ['q'=>'How do you redirect from a controller?',                                       'd'=>'easy',   'o'=>["A) return redirect('/url')","B) return redirect()->to('/url')","C) Both A and B","D) return header('Location: /url')"],         'a'=>'C) Both A and B'],
                ['q'=>'How do you redirect to a named route from a controller?',                      'd'=>'medium', 'o'=>["A) return redirect()->route('name')","B) return redirect('name')","C) return route()->redirect('name')","D) return back()->route('name')"], 'a'=>"A) return redirect()->route('name')"],
                ['q'=>'What method returns the previous URL redirect?',                               'd'=>'easy',   'o'=>["A) return back()","B) return previous()","C) return redirect()->previous()","D) return go()->back()"],                          'a'=>"A) return back()"],
                ['q'=>'How do you flash data to the session in a redirect?',                          'd'=>'medium', 'o'=>["A) return redirect('/url')->with('key', 'value')","B) session()->flash('key', 'value'); return redirect('/url')","C) Both A and B","D) return redirect('/url')->flash('key', 'value')"], 'a'=>'C) Both A and B'],
                ['q'=>'How do you pass data to a view from a controller?',                            'd'=>'easy',   'o'=>["A) view('name', ['key' => \$val])","B) view('name')->with('key', \$val)","C) Both A and B","D) view('name')->data(['key' => \$val])"], 'a'=>'C) Both A and B'],
                ['q'=>'What HTTP status code does a 201 response indicate?',                          'd'=>'easy',   'o'=>['A) OK','B) Created','C) Accepted','D) No Content'],                                                                            'a'=>'B) Created'],
                ['q'=>'How do you return a 404 response from a controller?',                          'd'=>'medium', 'o'=>["A) abort(404)","B) return response(404)","C) throw new NotFoundException()","D) return 404"],                                   'a'=>"A) abort(404)"],
                ['q'=>'What does the authorize() method in a controller do?',                         'd'=>'hard',   'o'=>['A) Runs DB auth queries','B) Checks a policy/gate and throws 403 if denied','C) Logs the user in','D) Validates the API token'], 'a'=>'B) Checks a policy/gate and throws 403 if denied'],
                ['q'=>'What is API resource controller missing compared to a full resource controller?','d'=>'hard', 'o'=>['A) index and show','B) create and edit (view-returning methods)','C) store and update','D) destroy'],                           'a'=>'B) create and edit (view-returning methods)'],
                ['q'=>'How do you create an API resource controller?',                                'd'=>'medium', 'o'=>['A) php artisan make:controller Name --api','B) php artisan make:controller Name --resource --api','C) Both A and B','D) php artisan api:controller Name'], 'a'=>'A) php artisan make:controller Name --api'],
                ['q'=>'What does return response()->noContent() return?',                             'd'=>'medium', 'o'=>['A) HTTP 200 with empty body','B) HTTP 204 No Content','C) HTTP 404','D) HTTP 304 Not Modified'],                                'a'=>'B) HTTP 204 No Content'],
                ['q'=>'How do you download a file from a controller?',                                'd'=>'hard',   'o'=>["A) return response()->download(\$path)","B) return file(\$path)","C) return stream(\$path)","D) return sendFile(\$path)"],       'a'=>"A) return response()->download(\$path)"],
                ['q'=>'What is constructor injection vs method injection in controllers?',             'd'=>'hard',   'o'=>['A) No difference','B) Constructor injection shares across all methods; method injection is per-action','C) Method injection is faster','D) Constructor injection only works with services'], 'a'=>'B) Constructor injection shares across all methods; method injection is per-action'],
            ],

            // ── MODELS / ELOQUENT ─────────────────────────────────────────────
            'model' => [
                ['q'=>'What ORM does Laravel use?',                                                   'd'=>'easy',   'o'=>['A) Doctrine','B) RedBeanPHP','C) Eloquent','D) Propel'],                                                                       'a'=>'C) Eloquent'],
                ['q'=>'How do you create a new model in Laravel?',                                    'd'=>'easy',   'o'=>['A) php artisan make:model Name','B) php artisan create:model Name','C) php artisan new:model Name','D) php artisan generate:model Name'], 'a'=>'A) php artisan make:model Name'],
                ['q'=>'What property defines the table name for a model?',                            'd'=>'medium', 'o'=>['A) $table','B) $name','C) $entity','D) $from'],                                                                               'a'=>'A) $table'],
                ['q'=>'What property defines the primary key for a model?',                           'd'=>'medium', 'o'=>['A) $key','B) $primaryKey','C) $id','D) $pk'],                                                                                 'a'=>'B) $primaryKey'],
                ['q'=>'What does Model::all() do?',                                                   'd'=>'easy',   'o'=>['A) Deletes all records','B) Returns all rows as a collection','C) Counts all rows','D) Truncates the table'],                  'a'=>'B) Returns all rows as a collection'],
                ['q'=>'How do you find a model by primary key?',                                      'd'=>'easy',   'o'=>['A) Model::get($id)','B) Model::find($id)','C) Model::first($id)','D) Model::search($id)'],                                     'a'=>'B) Model::find($id)'],
                ['q'=>'What is the difference between find() and findOrFail()?',                      'd'=>'medium', 'o'=>['A) No difference','B) findOrFail() throws 404 if not found','C) findOrFail() returns null if not found','D) find() throws an exception'], 'a'=>'B) findOrFail() throws 404 if not found'],
                ['q'=>'What does Model::create($data) require in the model?',                         'd'=>'medium', 'o'=>['A) $hidden property','B) $fillable or $guarded property','C) $casts property','D) $rules property'],                          'a'=>'B) $fillable or $guarded property'],
                ['q'=>'What is mass assignment protection in Eloquent?',                               'd'=>'hard',   'o'=>['A) Preventing bulk deletes','B) Guarding attributes from being set via arrays','C) Encrypting mass data','D) Rate-limiting model writes'], 'a'=>'B) Guarding attributes from being set via arrays'],
                ['q'=>'How do you define a hasMany relationship?',                                     'd'=>'medium', 'o'=>["A) return \$this->hasMany(RelatedModel::class)","B) return \$this->many(RelatedModel::class)","C) return \$this->belongsToMany(RelatedModel::class)","D) return \$this->manyTo(RelatedModel::class)"], 'a'=>"A) return \$this->hasMany(RelatedModel::class)"],
                ['q'=>'How do you define a belongsTo relationship?',                                  'd'=>'medium', 'o'=>["A) return \$this->ownedBy(RelatedModel::class)","B) return \$this->belongsTo(RelatedModel::class)","C) return \$this->hasOne(RelatedModel::class)","D) return \$this->childOf(RelatedModel::class)"], 'a'=>"B) return \$this->belongsTo(RelatedModel::class)"],
                ['q'=>'What are Eloquent scopes used for?',                                            'd'=>'hard',   'o'=>['A) Defining permissions','B) Reusable query constraints','C) Transforming output','D) Caching queries'],                       'a'=>'B) Reusable query constraints'],
                ['q'=>'How do you define a local scope?',                                              'd'=>'hard',   'o'=>['A) function scopeName($query) in the model','B) function localScope($query) in the model','C) static function name($query)','D) scope::define(name, fn)'], 'a'=>'A) function scopeName($query) in the model'],
                ['q'=>'What does the $casts property do in a model?',                                  'd'=>'medium', 'o'=>['A) Hides attributes from JSON','B) Converts attribute types automatically','C) Encrypts attributes','D) Validates attribute values'], 'a'=>'B) Converts attribute types automatically'],
                ['q'=>'How do you soft-delete records in Eloquent?',                                   'd'=>'medium', 'o'=>['A) Use SoftDeletes trait and deleted_at column','B) Set $softDelete = true','C) Override delete() to set is_deleted','D) Use Model::trash()'], 'a'=>'A) Use SoftDeletes trait and deleted_at column'],
                ['q'=>'How do you include soft-deleted records in a query?',                           'd'=>'hard',   'o'=>['A) Model::withTrashed()->get()','B) Model::includeTrashed()->get()','C) Model::all(true)->get()','D) Model::withDeleted()->get()'], 'a'=>'A) Model::withTrashed()->get()'],
                ['q'=>'What does Model::firstOrCreate($attributes) do?',                               'd'=>'hard',   'o'=>['A) Always creates a new record','B) Finds the first matching record or creates it','C) Updates if exists, creates if not','D) Returns first record regardless of attributes'], 'a'=>'B) Finds the first matching record or creates it'],
                ['q'=>'What is eager loading in Eloquent?',                                            'd'=>'hard',   'o'=>['A) Loading all models at startup','B) Loading relationships upfront to avoid N+1 queries','C) Caching frequently accessed models','D) Loading only IDs for performance'], 'a'=>'B) Loading relationships upfront to avoid N+1 queries'],
                ['q'=>'How do you eager load a relationship?',                                         'd'=>'medium', 'o'=>["A) Model::load('relation')->get()","B) Model::with('relation')->get()","C) Model::join('relation')->get()","D) Model::include('relation')->get()"], 'a'=>"B) Model::with('relation')->get()"],
                ['q'=>'What Eloquent event fires after a model is saved?',                             'd'=>'hard',   'o'=>['A) afterSave','B) saved','C) postSave','D) stored'],                                                                          'a'=>'B) saved'],
                ['q'=>'How do you define a many-to-many relationship?',                                'd'=>'hard',   'o'=>["A) return \$this->hasMany(Related::class)","B) return \$this->belongsToMany(Related::class)","C) return \$this->manyToMany(Related::class)","D) return \$this->hasManyThrough(Related::class)"], 'a'=>"B) return \$this->belongsToMany(Related::class)"],
                ['q'=>'What does $model->fresh() do?',                                                 'd'=>'hard',   'o'=>['A) Resets model to default values','B) Returns a new instance reloaded from DB','C) Clears model cache','D) Soft-deletes and restores the model'], 'a'=>'B) Returns a new instance reloaded from DB'],
                ['q'=>'What does $model->refresh() do?',                                               'd'=>'hard',   'o'=>['A) Same as fresh() but mutates the current instance','B) Clears query cache','C) Resets fillable fields','D) Reloads relationships only'], 'a'=>'A) Same as fresh() but mutates the current instance'],
                ['q'=>'How do you update a model using Eloquent?',                                     'd'=>'easy',   'o'=>["A) \$model->update(['field' => 'value'])","B) \$model->save(['field' => 'value'])","C) Model::update(\$id, ['field' => 'value'])","D) \$model->set(['field' => 'value'])"], 'a'=>"A) \$model->update(['field' => 'value'])"],
                ['q'=>'What is an Eloquent observer?',                                                 'd'=>'hard',   'o'=>['A) A debug tool for queries','B) A class that listens to model lifecycle events','C) A query cache watcher','D) A DB trigger equivalent'], 'a'=>'B) A class that listens to model lifecycle events'],
            ],

            // ── MIGRATIONS ────────────────────────────────────────────────────
            'migration' => [
                ['q'=>'What is a migration in Laravel?',                                              'd'=>'easy',   'o'=>['A) Moving files between servers','B) Version control for the database schema','C) Exporting data to CSV','D) Syncing models with the DB'], 'a'=>'B) Version control for the database schema'],
                ['q'=>'How do you run all pending migrations?',                                       'd'=>'easy',   'o'=>['A) php artisan db:migrate','B) php artisan migrate','C) php artisan migration:run','D) php artisan schema:update'],              'a'=>'B) php artisan migrate'],
                ['q'=>'How do you rollback the last migration batch?',                                'd'=>'easy',   'o'=>['A) php artisan migrate:undo','B) php artisan migrate:rollback','C) php artisan rollback','D) php artisan migrate:revert'],       'a'=>'B) php artisan migrate:rollback'],
                ['q'=>'How do you rollback all migrations and re-run them?',                          'd'=>'medium', 'o'=>['A) php artisan migrate:refresh','B) php artisan migrate:reset && migrate','C) php artisan migrate:redo','D) php artisan migrate:restart'], 'a'=>'A) php artisan migrate:refresh'],
                ['q'=>'How do you create a new migration file?',                                      'd'=>'easy',   'o'=>['A) php artisan make:migration name','B) php artisan create:migration name','C) php artisan new:migration name','D) php artisan migration:create name'], 'a'=>'A) php artisan make:migration name'],
                ['q'=>'What method adds a column in a migration?',                                    'd'=>'medium', 'o'=>['A) $table->addColumn()','B) $table->column()','C) $table->string() / $table->integer() etc.','D) $table->add()'],               'a'=>'C) $table->string() / $table->integer() etc.'],
                ['q'=>'What method is called when rolling back a migration?',                         'd'=>'easy',   'o'=>['A) down()','B) rollback()','C) revert()','D) undo()'],                                                                         'a'=>'A) down()'],
                ['q'=>'How do you add an index to a column in a migration?',                          'd'=>'medium', 'o'=>["A) ->index()","B) ->addIndex()","C) ->indexed()","D) ->key()"],                                                                'a'=>"A) ->index()"],
                ['q'=>'How do you add a unique constraint to a column?',                              'd'=>'medium', 'o'=>["A) ->unique()","B) ->onlyUnique()","C) ->distinct()","D) ->singular()"],                                                       'a'=>"A) ->unique()"],
                ['q'=>'What column type stores large text in a migration?',                           'd'=>'medium', 'o'=>['A) $table->string()','B) $table->text()','C) $table->longText()','D) Both B and C depending on size'],                         'a'=>'D) Both B and C depending on size'],
                ['q'=>'How do you add timestamps (created_at, updated_at) to a table?',              'd'=>'easy',   'o'=>['A) $table->timestamps()','B) $table->addTimestamps()','C) $table->dates()','D) $table->times()'],                               'a'=>'A) $table->timestamps()'],
                ['q'=>'What does $table->softDeletes() add?',                                         'd'=>'medium', 'o'=>['A) A boolean is_deleted column','B) A deleted_at nullable timestamp column','C) Triggers a DB soft-delete','D) An archived_at column'], 'a'=>'B) A deleted_at nullable timestamp column'],
                ['q'=>'How do you add a foreign key constraint in a migration?',                      'd'=>'hard',   'o'=>["A) \$table->foreign('col')->references('id')->on('table')","B) \$table->foreignKey('col', 'table')","C) \$table->references('col', 'table')","D) \$table->link('col', 'table')"], 'a'=>"A) \$table->foreign('col')->references('id')->on('table')"],
                ['q'=>'What does Schema::dropIfExists() do?',                                         'd'=>'easy',   'o'=>['A) Drops a table only if it exists','B) Truncates the table','C) Removes a column','D) Rolls back migrations'],               'a'=>'A) Drops a table only if it exists'],
                ['q'=>'How do you make a column nullable in a migration?',                            'd'=>'easy',   'o'=>["A) ->nullable()","B) ->optional()","C) ->allowNull()","D) ->null()"],                                                          'a'=>"A) ->nullable()"],
                ['q'=>'How do you add a default value to a column?',                                  'd'=>'easy',   'o'=>["A) ->default(value)","B) ->defaultsTo(value)","C) ->setValue(value)","D) ->fallback(value)"],                                  'a'=>"A) ->default(value)"],
                ['q'=>'How do you modify an existing column in a migration?',                         'd'=>'hard',   'o'=>['A) Use ->change() after redefining the column (requires doctrine/dbal or native)','B) Drop and recreate the column','C) Use ALTER_TABLE artisan command','D) Edit the original migration'], 'a'=>'A) Use ->change() after redefining the column (requires doctrine/dbal or native)'],
                ['q'=>'What does php artisan migrate:status show?',                                   'd'=>'medium', 'o'=>['A) DB connection status','B) List of migrations and whether they have been run','C) Pending queue jobs','D) Schema version'],  'a'=>'B) List of migrations and whether they have been run'],
                ['q'=>'What does php artisan migrate:fresh do?',                                      'd'=>'medium', 'o'=>['A) Creates a fresh migration file','B) Drops all tables and re-runs all migrations','C) Rolls back one batch','D) Refreshes DB config'], 'a'=>'B) Drops all tables and re-runs all migrations'],
                ['q'=>'How do you add a composite primary key in a migration?',                       'd'=>'hard',   'o'=>["A) \$table->primary(['col1','col2'])","B) \$table->compositeKey(['col1','col2'])","C) \$table->multiPrimary('col1','col2')","D) \$table->primaryKey(['col1','col2'])"], 'a'=>"A) \$table->primary(['col1','col2'])"],
                ['q'=>'What migration column type maps to a BIGINT auto-increment primary key?',      'd'=>'medium', 'o'=>['A) $table->id()','B) $table->bigInteger()->autoIncrement()','C) Both A and B','D) $table->primary()'],                          'a'=>'C) Both A and B'],
                ['q'=>'How do you rename a column in a migration?',                                   'd'=>'hard',   'o'=>["A) \$table->renameColumn('old','new')","B) \$table->rename('old','new')","C) Schema::rename('old','new')","D) \$table->changeColumn('old','new')"], 'a'=>"A) \$table->renameColumn('old','new')"],
                ['q'=>'How do you rename a table in a migration?',                                    'd'=>'hard',   'o'=>["A) Schema::rename('old','new')","B) DB::renameTable('old','new')","C) \$table->renameTo('new')","D) Schema::table('old')->rename('new')"], 'a'=>"A) Schema::rename('old','new')"],
                ['q'=>'What does the --seed flag do with migrate:fresh?',                             'd'=>'medium', 'o'=>['A) Adds test columns','B) Runs seeders after migrating','C) Generates fake data columns','D) Seeds the cache'],               'a'=>'B) Runs seeders after migrating'],
                ['q'=>'What column type stores a UUID in a migration?',                               'd'=>'medium', 'o'=>['A) $table->uuid()','B) $table->guid()','C) $table->string(36)','D) Both A and C'],                                            'a'=>'A) $table->uuid()'],
            ],

            // ── VALIDATION ────────────────────────────────────────────────────
            'validat' => [
                ['q'=>'How do you validate a request in a Laravel controller?',                       'd'=>'easy',   'o'=>["A) \$request->validate([...])","B) Validator::run([...])","C) \$this->check([...])","D) validate(\$request)"],                  'a'=>"A) \$request->validate([...])"],
                ['q'=>'What happens if validation fails in $request->validate()?',                    'd'=>'medium', 'o'=>['A) Returns null','B) Redirects back with errors','C) Throws an exception silently','D) Returns false'],                        'a'=>'B) Redirects back with errors'],
                ['q'=>'How do you access validation errors in a Blade view?',                         'd'=>'medium', 'o'=>['A) $errors->all()','B) session("errors")','C) $validationErrors','D) request()->errors()'],                                   'a'=>'A) $errors->all()'],
                ['q'=>'What validation rule ensures a field is present and not empty?',               'd'=>'easy',   'o'=>['A) present','B) filled','C) required','D) exists'],                                                                           'a'=>'C) required'],
                ['q'=>'What is the difference between required and required_if?',                     'd'=>'medium', 'o'=>['A) No difference','B) required_if makes the field required based on another field value','C) required_if only applies to checkboxes','D) required_if is deprecated'], 'a'=>'B) required_if makes the field required based on another field value'],
                ['q'=>'How do you validate that a field is a valid email?',                           'd'=>'easy',   'o'=>["A) 'email'","B) 'email:rfc,dns'","C) Both work","D) 'is_email'"],                                                              'a'=>'C) Both work'],
                ['q'=>'What rule checks if a value exists in a DB table?',                            'd'=>'medium', 'o'=>["A) 'in_db:table,column'","B) 'exists:table,column'","C) 'db:table,column'","D) 'found:table,column'"],                        'a'=>"B) 'exists:table,column'"],
                ['q'=>'What rule checks if a value is unique in a DB table?',                         'd'=>'medium', 'o'=>["A) 'unique:table,column'","B) 'distinct:table,column'","C) 'notExists:table,column'","D) 'singular:table,column'"],           'a'=>"A) 'unique:table,column'"],
                ['q'=>'How do you ignore the current model ID when validating unique fields on update?','d'=>'hard', 'o'=>["A) Rule::unique('table')->ignore(\$model->id)","B) 'unique:table,column,except,id'","C) Both A and B","D) 'unique:table,column,ignore:\$id'"], 'a'=>'C) Both A and B'],
                ['q'=>'What rule validates an integer?',                                              'd'=>'easy',   'o'=>["A) 'number'","B) 'int'","C) 'integer'","D) 'numeric_integer'"],                                                               'a'=>"C) 'integer'"],
                ['q'=>'What rule validates either an integer or decimal number?',                     'd'=>'easy',   'o'=>["A) 'float'","B) 'decimal'","C) 'numeric'","D) 'number'"],                                                                     'a'=>"C) 'numeric'"],
                ['q'=>'How do you set a maximum string length in validation?',                        'd'=>'easy',   'o'=>["A) 'max:255'","B) 'maxLength:255'","C) 'limit:255'","D) 'length:0,255'"],                                                      'a'=>"A) 'max:255'"],
                ['q'=>'What rule validates an array field?',                                          'd'=>'medium', 'o'=>["A) 'list'","B) 'collection'","C) 'array'","D) 'multiple'"],                                                                   'a'=>"C) 'array'"],
                ['q'=>'How do you validate each item inside an array?',                               'd'=>'hard',   'o'=>["A) 'items.*.rule'","B) 'array.*.rule'","C) 'items[*].rule'","D) Use wildcard: 'field.*.rule'"],                               'a'=>"D) Use wildcard: 'field.*.rule'"],
                ['q'=>'What is a Form Request and how does it differ from inline validation?',        'd'=>'hard',   'o'=>['A) It is faster','B) A dedicated class with rules() and authorize() methods','C) It works only for API routes','D) It skips middleware'], 'a'=>'B) A dedicated class with rules() and authorize() methods'],
                ['q'=>'How do you create a Form Request?',                                            'd'=>'medium', 'o'=>['A) php artisan make:request Name','B) php artisan make:formrequest Name','C) php artisan create:request Name','D) php artisan new:request Name'], 'a'=>'A) php artisan make:request Name'],
                ['q'=>'What does the authorize() method in a Form Request do?',                       'd'=>'medium', 'o'=>['A) Authenticates the user','B) Determines if the user is allowed to make this request','C) Validates the token','D) Runs before middleware'], 'a'=>'B) Determines if the user is allowed to make this request'],
                ['q'=>'How do you add custom error messages in a Form Request?',                      'd'=>'hard',   'o'=>["A) Override the messages() method","B) Add a \$messages property","C) Pass messages as 3rd arg to validate()","D) Both A and C"], 'a'=>'D) Both A and C'],
                ['q'=>'What rule validates a file upload?',                                           'd'=>'medium', 'o'=>["A) 'upload'","B) 'file'","C) 'attachment'","D) 'binary'"],                                                                    'a'=>"B) 'file'"],
                ['q'=>'What rule validates an image upload?',                                         'd'=>'medium', 'o'=>["A) 'photo'","B) 'image'","C) 'picture'","D) 'img'"],                                                                          'a'=>"B) 'image'"],
                ['q'=>'How do you allow a field to be absent or null?',                               'd'=>'medium', 'o'=>["A) 'optional'","B) 'nullable'","C) 'sometimes'","D) Both B and C"],                                                            'a'=>"D) Both B and C"],
                ['q'=>'What does the sometimes rule do?',                                             'd'=>'hard',   'o'=>['A) Validates only on certain days','B) Applies rules only if the field is present in the request','C) Makes the field required sometimes','D) Skips validation randomly'], 'a'=>'B) Applies rules only if the field is present in the request'],
                ['q'=>'How do you validate that two fields match (e.g. password confirmation)?',      'd'=>'medium', 'o'=>["A) 'confirmed'","B) 'match:field'","C) 'same:field'","D) Both A and C work"],                                                  'a'=>"D) Both A and C work"],
                ['q'=>'What does the bail rule do?',                                                  'd'=>'hard',   'o'=>['A) Stops all validation','B) Stops validating a field after the first failure','C) Throws an exception','D) Logs validation errors'], 'a'=>'B) Stops validating a field after the first failure'],
                ['q'=>'How do you validate a date field?',                                            'd'=>'medium', 'o'=>["A) 'date'","B) 'datetime'","C) 'timestamp'","D) 'carbon'"],                                                                   'a'=>"A) 'date'"],
            ],

            // ── AUTH ──────────────────────────────────────────────────────────
            'auth' => [
                ['q'=>'Which Laravel package provides pre-built authentication scaffolding?',          'd'=>'easy',   'o'=>['A) laravel/auth','B) laravel/breeze or laravel/jetstream','C) laravel/passport only','D) laravel/sanctum only'],              'a'=>'B) laravel/breeze or laravel/jetstream'],
                ['q'=>'How do you get the currently authenticated user?',                             'd'=>'easy',   'o'=>['A) Auth::user()','B) auth()->user()','C) $request->user()','D) All of the above'],                                            'a'=>'D) All of the above'],
                ['q'=>'How do you check if a user is authenticated?',                                 'd'=>'easy',   'o'=>['A) Auth::check()','B) auth()->check()','C) Both A and B','D) Auth::isLoggedIn()'],                                            'a'=>'C) Both A and B'],
                ['q'=>'How do you log a user in programmatically?',                                   'd'=>'medium', 'o'=>['A) Auth::login($user)','B) auth()->login($user)','C) Both A and B','D) session()->login($user)'],                              'a'=>'C) Both A and B'],
                ['q'=>'How do you log a user out?',                                                   'd'=>'easy',   'o'=>['A) Auth::logout()','B) auth()->logout()','C) Both A and B','D) session()->destroy()'],                                        'a'=>'C) Both A and B'],
                ['q'=>'What does Auth::attempt($credentials) do?',                                    'd'=>'medium', 'o'=>['A) Creates a new user','B) Verifies credentials and logs in the user if valid','C) Resets the password','D) Generates a token'], 'a'=>'B) Verifies credentials and logs in the user if valid'],
                ['q'=>'Which Laravel package provides API token authentication?',                      'd'=>'medium', 'o'=>['A) laravel/auth','B) laravel/passport or laravel/sanctum','C) laravel/jwt','D) laravel/api'],                                'a'=>'B) laravel/passport or laravel/sanctum'],
                ['q'=>'What is the difference between Sanctum and Passport?',                         'd'=>'hard',   'o'=>['A) No difference','B) Sanctum is lightweight (tokens/SPA); Passport is full OAuth2','C) Passport is for mobile, Sanctum for web','D) Sanctum requires Redis'], 'a'=>'B) Sanctum is lightweight (tokens/SPA); Passport is full OAuth2'],
                ['q'=>'How do you protect a route to require authentication?',                        'd'=>'easy',   'o'=>["A) ->middleware('auth')","B) ->protected()","C) ->requireAuth()","D) ->guard('web')"],                                        'a'=>"A) ->middleware('auth')"],
                ['q'=>'What is a Gate in Laravel authorization?',                                     'd'=>'hard',   'o'=>['A) A DB access layer','B) A closure-based authorization check','C) A route guard','D) A session handler'],                   'a'=>'B) A closure-based authorization check'],
                ['q'=>'What is a Policy in Laravel?',                                                 'd'=>'hard',   'o'=>['A) A config file','B) A class organizing authorization logic around a model','C) A middleware','D) A validation rule'],        'a'=>'B) A class organizing authorization logic around a model'],
                ['q'=>'How do you create a policy?',                                                  'd'=>'medium', 'o'=>['A) php artisan make:policy Name --model=Model','B) php artisan create:policy Name','C) php artisan new:policy Name','D) php artisan generate:policy Name'], 'a'=>'A) php artisan make:policy Name --model=Model'],
                ['q'=>'How do you authorize an action using a policy in a controller?',               'd'=>'hard',   'o'=>["A) \$this->authorize('action', \$model)","B) Policy::check('action', \$model)","C) Auth::can('action', \$model)","D) Gate::allows('action', \$model)"], 'a'=>"A) \$this->authorize('action', \$model)"],
                ['q'=>'What does Gate::allows() return?',                                             'd'=>'medium', 'o'=>['A) The user object','B) true or false','C) An HTTP response','D) The gate policy class'],                                     'a'=>'B) true or false'],
                ['q'=>'How do you check a gate/policy in Blade?',                                     'd'=>'medium', 'o'=>["A) @can('action', \$model) ... @endcan","B) @if(auth()->can('action')) ... @endif","C) Both A and B","D) @gate('action') ... @endgate"], 'a'=>'C) Both A and B'],
                ['q'=>'What is the remember me functionality in Auth::attempt()?',                    'd'=>'medium', 'o'=>["A) Auth::attempt(\$creds, \$remember=true)","B) Auth::loginWithRemember(\$creds)","C) Auth::attempt(\$creds, \$request->remember)","D) Both A and C"], 'a'=>'D) Both A and C'],
                ['q'=>'How do you get the authenticated user\'s ID?',                                 'd'=>'easy',   'o'=>['A) Auth::id()','B) auth()->id()','C) Both A and B','D) Auth::user()->id'],                                                    'a'=>'C) Both A and B'],
                ['q'=>'What does the verified middleware do?',                                        'd'=>'medium', 'o'=>['A) Verifies the API token','B) Ensures the user has verified their email address','C) Checks 2FA','D) Validates the CSRF token'], 'a'=>'B) Ensures the user has verified their email address'],
                ['q'=>'What interface must a model implement to use email verification?',             'd'=>'hard',   'o'=>['A) Verifiable','B) MustVerifyEmail','C) HasEmailVerification','D) EmailVerifiable'],                                            'a'=>'B) MustVerifyEmail'],
                ['q'=>'How do you generate a personal access token with Sanctum?',                    'd'=>'hard',   'o'=>["A) \$user->createToken('name')->plainTextToken","B) Sanctum::generate(\$user, 'name')","C) \$user->token('name')","D) Auth::token(\$user, 'name')"], 'a'=>"A) \$user->createToken('name')->plainTextToken"],
                ['q'=>'How do you revoke all tokens for a user in Sanctum?',                          'd'=>'hard',   'o'=>['A) $user->tokens()->delete()','B) Sanctum::revokeAll($user)','C) $user->revokeTokens()','D) Auth::deleteTokens($user)'],        'a'=>'A) $user->tokens()->delete()'],
                ['q'=>'What is the default guard in Laravel?',                                        'd'=>'medium', 'o'=>['A) api','B) token','C) web','D) session'],                                                                                    'a'=>'C) web'],
                ['q'=>'How do you switch guards?',                                                    'd'=>'hard',   'o'=>["A) Auth::guard('api')->user()","B) auth('api')->user()","C) Both A and B","D) Auth::use('api')->user()"],                        'a'=>'C) Both A and B'],
                ['q'=>'What does Auth::viaRemember() return?',                                        'd'=>'hard',   'o'=>['A) The remember token','B) true if the user was authenticated via a remember cookie','C) false always','D) The remember cookie lifetime'], 'a'=>'B) true if the user was authenticated via a remember cookie'],
                ['q'=>'How do you log in once (without session) in Laravel?',                         'd'=>'hard',   'o'=>['A) Auth::once($credentials)','B) Auth::loginOnce($user)','C) auth()->once($credentials)','D) Both A and C'],                  'a'=>'D) Both A and C'],
            ],
        ];

        // ── Pick the best matching bank ───────────────────────────────────────
        $lowerTopic = strtolower($topic);
        $selectedBank = null;

        foreach ($banks as $keyword => $bank) {
            if (strpos($lowerTopic, $keyword) !== false) {
                $selectedBank = $bank;
                break;
            }
        }

        // Fall back to a merged pool of all banks
        if (!$selectedBank) {
            $selectedBank = array_merge(...array_values($banks));
            shuffle($selectedBank);
        }

        // ── Build distribution ────────────────────────────────────────────────
        $easyCount   = max(1, (int)($count * 0.30));
        $mediumCount = max(1, (int)($count * 0.50));
        $hardCount   = max(0, $count - $easyCount - $mediumCount);

        $dist = array_merge(
            array_fill(0, $easyCount,   'easy'),
            array_fill(0, $mediumCount, 'medium'),
            array_fill(0, $hardCount,   'hard')
        );
        shuffle($dist);

        // ── Assemble questions ────────────────────────────────────────────────
        $questions = [];
        for ($i = 0; $i < $count; $i++) {
            $tpl = $selectedBank[$i % count($selectedBank)];
            $questions[] = [
                'question_text' => $tpl['q'],
                'question_type' => 'multiple_choice',
                'difficulty'    => $dist[$i] ?? $tpl['d'],
                'options'       => $tpl['o'],
                'correct_answer'=> $tpl['a'],
            ];
        }

        return $questions;
    }

    private function calculatePoints(string $difficulty): int
    {
        return match (strtolower($difficulty)) {
            'easy'  => 1,
            'medium'=> 2,
            'hard'  => 5,
            default => 1,
        };
    }

    /**
     * Get all quizzes
     */
    public function index(): JsonResponse
{
    $userId = auth()->id();
    
    // Debug: Vérifier toutes les tentatives de l'utilisateur
    $allAttempts = QuizAttempt::where('user_id', $userId)->get();
    \Log::info('All attempts for user', [
        'user_id' => $userId,
        'attempts' => $allAttempts->map(fn($a) => [
            'attempt_id' => $a->id,
            'quiz_id' => $a->quiz_id,
            'score' => $a->score
        ])
    ]);

    $quizzes = Quiz::with('lesson', 'questions')
        ->withCount('questions')
        ->paginate(20);

    $quizzes->getCollection()->transform(function ($quiz) use ($userId) {
        
        // Debug: Vérifier pour ce quiz spécifique
        \Log::info('Looking for attempt', [
            'quiz_id' => $quiz->id,
            'quiz_title' => $quiz->title,
            'user_id' => $userId
        ]);
        
        $attempt = QuizAttempt::where('quiz_id', $quiz->id)
            ->where('user_id', $userId)
            ->latest()
            ->first();
        
        \Log::info('Attempt found', [
            'quiz_id' => $quiz->id,
            'attempt_exists' => $attempt ? true : false,
            'attempt_id' => $attempt?->id,
            'attempt_quiz_id' => $attempt?->quiz_id,
            'score' => $attempt?->score
        ]);
        
        $quiz->attempt_id = $attempt?->id;
        $quiz->attempt_exists = $attempt ? true : false;
        $quiz->user_score = $attempt ? (int) $attempt->score : null;
        return $quiz;
    });
    
    return response()->json($quizzes);
}
    /**
     * Get a specific quiz with its questions
     */
    public function show($id): JsonResponse
    {
        $quiz = Quiz::with('questions')->find($id);

        if (!$quiz) {
            return response()->json(['message' => 'Quiz not found'], 404);
        }

        return response()->json($quiz);
    }

    /**
     * Get quizzes by lesson
     */
    public function byLesson($lessonId): JsonResponse
    {
        $quizzes = Quiz::where('lesson_id', $lessonId)
            ->with('questions')
            ->get();

        return response()->json($quizzes);
    }

    /**
     * Create a manual quiz
     */
    public function store(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                'lesson_id'     => 'required|exists:lessons,id',
                'title'         => 'required|string|max:255',
                'description'   => 'nullable|string',
                'passing_score' => 'nullable|integer|min:0|max:100',
            ]);

            $quiz = Quiz::create(array_merge($validated, [
                'passing_score' => $validated['passing_score'] ?? 70,
                'is_published'  => false,
            ]));

            return response()->json($quiz, 201);
        } catch (\Exception $e) {
            return response()->json(['message' => $e->getMessage()], 400);
        }
    }

    /**
     * Update a quiz
     */
    public function update(Request $request, $id): JsonResponse
    {
        try {
            $quiz = Quiz::find($id);

            if (!$quiz) {
                return response()->json(['message' => 'Quiz not found'], 404);
            }

            $validated = $request->validate([
                'title'         => 'nullable|string|max:255',
                'description'   => 'nullable|string',
                'passing_score' => 'nullable|integer|min:0|max:100',
                'is_published'  => 'nullable|boolean',
            ]);

            $quiz->update($validated);

            return response()->json($quiz);
        } catch (\Exception $e) {
            return response()->json(['message' => $e->getMessage()], 400);
        }
    }

    /**
     * Delete a quiz
     */
    public function destroy($id): JsonResponse
    {
        try {
            $quiz = Quiz::find($id);

            if (!$quiz) {
                return response()->json(['message' => 'Quiz not found'], 404);
            }

            $quiz->delete();

            return response()->json(['message' => 'Quiz deleted successfully']);
        } catch (\Exception $e) {
            return response()->json(['message' => $e->getMessage()], 400);
        }
    }

    /**
     * Add a question to quiz
     */
    public function addQuestion(Request $request, $quizId): JsonResponse
    {
        try {
            $quiz = Quiz::find($quizId);
            if (!$quiz) {
                return response()->json(['message' => 'Quiz not found'], 404);
            }

            $validated = $request->validate([
                'question_text' => 'required|string',
                'question_type' => 'required|in:multiple_choice,true_false,short_answer',
                'options'       => 'nullable|array',
                'correct_answer'=> 'required|string',
                'difficulty'    => 'nullable|in:easy,medium,hard',
                'points'        => 'nullable|integer|min:1',
                'order'         => 'nullable|integer',
            ]);

            $question = $quiz->questions()->create(array_merge($validated, [
                'difficulty' => $validated['difficulty'] ?? 'medium',
                'points'     => $validated['points'] ?? 1,
            ]));

            return response()->json($question, 201);
        } catch (\Exception $e) {
            return response()->json(['message' => $e->getMessage()], 400);
        }
    }

    /**
     * Update a question
     */
    public function updateQuestion(Request $request, $id): JsonResponse
    {
        try {
            $question = QuizQuestion::find($id);
            if (!$question) {
                return response()->json(['message' => 'Question not found'], 404);
            }

            $validated = $request->validate([
                'question_text' => 'nullable|string',
                'question_type' => 'nullable|in:multiple_choice,true_false,short_answer',
                'options'       => 'nullable|json',
                'correct_answer'=> 'nullable|string',
                'difficulty'    => 'nullable|in:easy,medium,hard',
                'points'        => 'nullable|integer|min:1',
                'order'         => 'nullable|integer',
            ]);

            $question->update($validated);

            return response()->json($question);
        } catch (\Exception $e) {
            return response()->json(['message' => $e->getMessage()], 400);
        }
    }

    /**
     * Delete a question
     */
    public function deleteQuestion($id): JsonResponse
    {
        try {
            $question = QuizQuestion::find($id);
            if (!$question) {
                return response()->json(['message' => 'Question not found'], 404);
            }

            $question->delete();

            return response()->json(['message' => 'Question deleted successfully']);
        } catch (\Exception $e) {
            return response()->json(['message' => $e->getMessage()], 400);
        }
    }

    /**
     * Submit a quiz attempt
     */
    public function submitAttempt(Request $request, $quizId): JsonResponse
    {
        try {
            $quiz = Quiz::with('questions')->find($quizId);
            if (!$quiz) {
                return response()->json(['message' => 'Quiz not found'], 404);
            }

            $validated = $request->validate([
                'answers' => 'required|array',
            ]);

            // Normalise answer keys to strings so both "12" and 12 match $question->id
            $answers = array_combine(
                array_map('strval', array_keys($validated['answers'])),
                array_values($validated['answers'])
            );

            $score       = 0;
            $totalPoints = 0;

            foreach ($quiz->questions as $question) {
                $points       = (int) ($question->points ?? 1);
                $totalPoints += $points;

                $key = (string) $question->id;

                if (!array_key_exists($key, $answers)) {
                    continue; // question was skipped
                }

                $userAnswer    = strtolower(trim((string) $answers[$key]));
                $correctAnswer = strtolower(trim((string) ($question->correct_answer ?? '')));

                // Also accept just the letter prefix (e.g. "b" matching "b) option text")
                $letterOnly = strtolower(trim(explode(')', (string)($question->correct_answer ?? ''))[0]));

                if ($userAnswer === $correctAnswer || $userAnswer === $letterOnly) {
                    $score += $points;
                }
            }

            $percentage = $totalPoints > 0 ? (int) round(($score / $totalPoints) * 100) : 0;
            $passed     = $percentage >= (int) ($quiz->passing_score ?? 70);

            $earnedXp = (int) round($percentage) + ($passed ? 50 : 0);

            // answers cast is 'array' in the model — pass the raw PHP array, NOT json_encode'd
            $attempt = QuizAttempt::create([
                'user_id'          => auth()->id(),
                'quiz_id'          => (int) $quizId,
                'score'            => $percentage,      // int 0–100
                'max_score'        => 100,
                'passed'           => (bool) $passed,
                'answers'          => $answers,         // array — model cast handles encoding
                'earned_xp'        => $earnedXp,
                'completed_at'     => now(),
            ]);

            // Safety net: if DB somehow stored null, force-patch it
            if ($attempt->score === null) {
                Log::warning('QUIZ_ATTEMPT_SCORE_NULL', [
                    'quiz_id'     => $quizId,
                    'user_id'     => auth()->id(),
                    'percentage'  => $percentage,
                    'totalPoints' => $totalPoints,
                    'raw_score'   => $score,
                ]);
                $attempt->forceFill(['score' => $percentage])->save();
            }

            // Award XP to user
            $user = auth()->user();
            $user->xp = (int)($user->xp ?? 0) + $earnedXp;
            $user->save();

            $awardedBadges = BadgeService::checkQuizBadges($user, $attempt);


            BadgeService::checkXpBadges($user);
            BadgeService::checkLevelBadges($user);
            BadgeService::checkSubjectBadges($user);
            BadgeService::checkStreakBadges($user);

            $badgeNames = collect($awardedBadges)->pluck('name')->toArray();

            return response()->json([
                'message'        => $passed ? 'Quiz passed!' : 'Quiz failed',
                'score'          => $attempt->score,   // use model value (never null)
                'correct'        => $score,
                'total_points'   => $totalPoints,
                'passed'         => $passed,
                'attempt_id'     => $attempt->id,
                'awarded_badges' => $badgeNames,
                'badge_count'    => count($awardedBadges),
                'xp_earned'      => $earnedXp,
            ]);
        } catch (\Exception $e) {
            return response()->json(['message' => $e->getMessage()], 400);
        }
    }

    /**
     * Get user's quiz attempts
     */
    public function userAttempts($quizId): JsonResponse
    {
        try {
            $attempts = QuizAttempt::where('quiz_id', $quizId)
                ->where('user_id', auth()->id())
                ->orderBy('completed_at', 'desc')
                ->get();

            return response()->json($attempts);
        } catch (\Exception $e) {
            return response()->json(['message' => $e->getMessage()], 400);
        }
    }

    /**
     * Generate quiz without storing (alternative endpoint)
     */
    public function generateQuiz(Request $request): JsonResponse
    {
        try {
            $validated = $request->validate([
                'lesson_id'       => 'required|exists:lessons,id',
                'questions_count' => 'nullable|integer|min:3|max:25',
            ]);

            $lesson       = Lesson::findOrFail($validated['lesson_id']);
            $cleanContent = mb_substr(strip_tags($lesson->content), 0, 5000);
            $count        = min((int)($request->questions_count ?? 5), self::MAX_QUESTIONS);

            if (!config('services.openai.key')) {
                throw new Exception("OpenAI API key is missing");
            }

            $questions = $this->fetchAiQuestions($cleanContent, $lesson->title, $count);

            return response()->json([
                'success'   => true,
                'questions' => $questions,
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
            ], 400);
        }
    }
}